services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sigdt
      - POSTGRES_PASSWORD=sigdt_pass
      - POSTGRES_DB=sigdt
    ports:
      - "5432:5432"

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sigdt:sigdt_pass@db:5432/sigdt
    depends_on:
      - db

volumes:
  postgres_data:
