"""initial_schema

Revision ID: aff112f79590
Revises: 
Create Date: 2026-04-01 08:46:52.774597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aff112f79590'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeronave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_serie', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aeronave', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aeronave_matricula'), ['matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_aeronave_numero_serie'), ['numero_serie'], unique=True)

    op.create_table('diretiva_tecnica',
    sa.Column('codigo_simplificado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('classe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('natureza', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('especialidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('codigo_simplificado')
    )
    with op.batch_alter_table('diretiva_tecnica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diretiva_tecnica_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_diretiva_tecnica_codigo_simplificado'), ['codigo_simplificado'], unique=False)
        batch_op.create_index(batch_op.f('ix_diretiva_tecnica_especialidade'), ['especialidade'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('especialidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('diretiva_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diretiva_tecnica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fadt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tarefa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ordem_referencia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chave_item', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao_item', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diretiva_tecnica_id'], ['diretiva_tecnica.codigo_simplificado'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diretiva_tecnica_id', 'chave_item')
    )
    with op.batch_alter_table('diretiva_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diretiva_item_chave_item'), ['chave_item'], unique=False)
        batch_op.create_index(batch_op.f('ix_diretiva_item_fadt'), ['fadt'], unique=False)

    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aeronave_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('nome_arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hash_conteudo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronave.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diretiva_item_aeronave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aeronave_id', sa.Integer(), nullable=False),
    sa.Column('diretiva_item_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_aplicacao', sa.DateTime(), nullable=True),
    sa.Column('data_status', sa.DateTime(), nullable=False),
    sa.Column('ordem_aplicada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tendencia', sa.Integer(), nullable=False),
    sa.Column('gut', sa.Float(), nullable=False),
    sa.Column('origem_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ultima_referencia_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('concluida_automaticamente', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronave.id'], ),
    sa.ForeignKeyConstraint(['diretiva_item_id'], ['diretiva_item.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aeronave_id', 'diretiva_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diretiva_item_aeronave')
    op.drop_table('snapshot')
    with op.batch_alter_table('diretiva_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diretiva_item_fadt'))
        batch_op.drop_index(batch_op.f('ix_diretiva_item_chave_item'))

    op.drop_table('diretiva_item')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('diretiva_tecnica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diretiva_tecnica_especialidade'))
        batch_op.drop_index(batch_op.f('ix_diretiva_tecnica_codigo_simplificado'))
        batch_op.drop_index(batch_op.f('ix_diretiva_tecnica_codigo'))

    op.drop_table('diretiva_tecnica')
    with op.batch_alter_table('aeronave', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aeronave_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_aeronave_matricula'))

    op.drop_table('aeronave')
    # ### end Alembic commands ###
