"""Init

Revision ID: b01e91b7be06
Revises: 
Create Date: 2026-03-21 15:03:09.898703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b01e91b7be06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Pre-emptively fill NULLs to satisfy NOT NULL constraint on old data
    op.execute("UPDATE diretiva SET fadt = 'TEMP-' || id WHERE fadt IS NULL OR fadt = '-'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diretiva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_diretiva', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='-'))
        batch_op.add_column(sa.Column('classe', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('natureza', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('fadt',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('objetivo',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_diretiva_diretiva_tecnica'))
        batch_op.drop_index(batch_op.f('ix_diretiva_sn_cjm'))
        batch_op.create_index(batch_op.f('ix_diretiva_codigo_diretiva'), ['codigo_diretiva'], unique=False)
        batch_op.create_index(batch_op.f('ix_diretiva_fadt'), ['fadt'], unique=True)
        batch_op.drop_column('diretiva_tecnica')
        batch_op.drop_column('sn')
        batch_op.drop_column('ultima_modificacao')
        batch_op.drop_column('gut')
        batch_op.drop_column('unidade')
        batch_op.drop_column('pj')
        batch_op.drop_column('tipo_incorporacao')
        batch_op.drop_column('cat')
        batch_op.drop_column('tarefa')
        batch_op.drop_column('cff')
        batch_op.drop_column('nat')
        batch_op.drop_column('pn')
        batch_op.drop_column('matr')
        batch_op.drop_column('pdf_path')
        batch_op.drop_column('cla')
        batch_op.drop_column('tendencia')
        batch_op.drop_column('status')
        batch_op.drop_column('prazo_incorporacao')
        batch_op.drop_column('horas')
        batch_op.drop_column('sn_cjm')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('rescisao')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diretiva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rescisao', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('sn_cjm', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('horas', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('prazo_incorporacao', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('tendencia', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('cla', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pdf_path', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('matr', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pn', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('nat', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('cff', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('tarefa', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('cat', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('tipo_incorporacao', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pj', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('unidade', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('gut', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('ultima_modificacao', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('sn', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('diretiva_tecnica', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_diretiva_fadt'))
        batch_op.drop_index(batch_op.f('ix_diretiva_codigo_diretiva'))
        batch_op.create_index(batch_op.f('ix_diretiva_sn_cjm'), ['sn_cjm'], unique=False)
        batch_op.create_index(batch_op.f('ix_diretiva_diretiva_tecnica'), ['diretiva_tecnica'], unique=False)
        batch_op.alter_column('objetivo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('fadt',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('natureza')
        batch_op.drop_column('tipo')
        batch_op.drop_column('categoria')
        batch_op.drop_column('classe')
        batch_op.drop_column('codigo_diretiva')

    # ### end Alembic commands ###
