"""feat: add new relational model for directives

Revision ID: e6ca8f306a0d
Revises: b01e91b7be06
Create Date: 2026-03-30 15:18:15.113084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e6ca8f306a0d'
down_revision: Union[str, Sequence[str], None] = 'b01e91b7be06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diretiva_tecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('classe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('natureza', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('especialidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diretiva_tecnica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diretiva_tecnica_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_diretiva_tecnica_especialidade'), ['especialidade'], unique=False)

    op.create_table('diretiva_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diretiva_tecnica_id', sa.Integer(), nullable=False),
    sa.Column('fadt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tarefa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ordem_referencia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chave_item', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao_item', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diretiva_tecnica_id'], ['diretiva_tecnica.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diretiva_tecnica_id', 'chave_item')
    )
    with op.batch_alter_table('diretiva_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diretiva_item_chave_item'), ['chave_item'], unique=False)
        batch_op.create_index(batch_op.f('ix_diretiva_item_fadt'), ['fadt'], unique=False)

    op.create_table('diretiva_item_aeronave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aeronave_id', sa.Integer(), nullable=False),
    sa.Column('diretiva_item_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_aplicacao', sa.DateTime(), nullable=True),
    sa.Column('data_status', sa.DateTime(), nullable=False),
    sa.Column('ordem_aplicada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tendencia', sa.Integer(), nullable=False),
    sa.Column('gut', sa.Float(), nullable=False),
    sa.Column('origem_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ultima_referencia_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('concluida_automaticamente', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronave.id'], ),
    sa.ForeignKeyConstraint(['diretiva_item_id'], ['diretiva_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aeronave_id', 'diretiva_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diretiva_item_aeronave')
    with op.batch_alter_table('diretiva_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diretiva_item_fadt'))
        batch_op.drop_index(batch_op.f('ix_diretiva_item_chave_item'))

    op.drop_table('diretiva_item')
    with op.batch_alter_table('diretiva_tecnica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diretiva_tecnica_especialidade'))
        batch_op.drop_index(batch_op.f('ix_diretiva_tecnica_codigo'))

    op.drop_table('diretiva_tecnica')
    # ### end Alembic commands ###
